language: python
python:
  - 2.7
  - 3.5
env:
  - DJANGO_VERSION=1.11.4
  - DJANGO_VERSION=1.10.7
install:
  - pip install -q Django==$DJANGO_VERSION
script:
  - cd kiwi
  - python manage.py migrate
  - python manage.py test
  - python manage.py bulk_create ../report.csv

