language: python
python:
  - 2.7
  - 3.5
env:
  - DJANGO_VERSION=1.7.8
  - DJANGO_VERSION=1.8.2
install:
  - pip install -q Django==$DJANGO_VERSION
script:
  - cd kiwi
  - python manage.py migrate
  - python manage.py bulk_create ../report.csv
  - python manage.py test

